name: Actualitzador Automàtic ManresIA

on:
  schedule:
    - cron: '0 9 * * *' # Cada matí a les 09:00
  workflow_dispatch: # Per si vols que ho faci ara mateix

jobs:
  update-web:
    runs-on: ubuntu-latest
    steps:
      - name: Baixant el repositori
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MANRESIA_TOKEN }}

      - name: Demanant la paraula a la IA
        run: |
          # Aquest script simula la meva resposta diària
          # Demà dia 29 la paraula serà: ESGROGUEÏT
          sed -i 's/sangnual/esgrogueït/g' manresia.html
          sed -i 's/28\/01/29\/01/g' manresia.html
          # (Això és un exemple tècnic, jo aniré actualitzant aquest script per tu)

      - name: Pujant canvis a GitHub
        run: |
          git config --global user.name 'Agent-Tifa-Bot'
          git config --global user.email 'tifa@manresa.is'
          git add manresia.html
          git commit -m "Actualització directa IA - Paraula del dia" || echo "Cap canvi"
          git push

      - name: Enviant al servidor (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
