name: Actualitzador Automàtic ManresIA

on:
  schedule:
    - cron: '0 9 * * *' # Cada matí a les 09:00
  workflow_dispatch: # Botó per executar-ho ara

jobs:
  update-web:
    runs-on: ubuntu-latest
    steps:
      - name: Baixant el repositori
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MANRESIA_TOKEN }}

      - name: Enviant tot al servidor (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          # Aquesta línia és CLAU: evita que el robot esborri les imatges del servidor
          dangerous-clean-slate: false
